# Generated by Django 4.1.7 on 2023-03-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'domaine',
                'verbose_name_plural': 'domaines',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.domaine')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('datenaissance', models.DateField()),
                ('genre', models.CharField(choices=[('1', 'Homme'), ('2', 'Femme')], default=1, max_length=8)),
                ('CV', models.FileField(upload_to='')),
                ('theme', models.ManyToManyField(related_name='formateur_theme_set', to='app.theme')),
            ],
            options={
                'verbose_name': 'formateur',
                'verbose_name_plural': 'formateurs',
            },
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CN', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('datenaissance', models.DateField()),
                ('genre', models.CharField(choices=[('1', 'Homme'), ('2', 'Femme')], default=1, max_length=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
            options={
                'verbose_name': 'beneficiaire',
                'verbose_name_plural': 'beneficiaires',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(default='non commencé', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateur')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.theme')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'unique_together': {('formateur', 'theme', 'client')},
            },
        ),
    ]
